# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Bun Backend CI

on:
  push:
    paths:
      - 'stayfinder-backend-bun/**'
      - '.github/workflows/node-ys.yml'
  pull_request:
    paths:
      - 'stayfinder-backend-bun/**'

jobs:
  backend-ci: # this is the name of the job basically
  
    runs-on: self-hosted # on my on ec2 lol
    defaults:
      run:
        working-directory: stayfinder-backend-bun/**

    steps:
    - uses: actions/checkout@v4
    - name: Check versions
      run: |
        node -v
        bun --version

    - name: Install dependencies
      run: bun install |
        touch .env
        echo "${{secrets.PROD_ENV_FILE}}"


     # - name: Run tests
     #   run: bun test

      # Optional build step (if needed)
      # - name: Build
      #   run: bun run build
